hi-i, I’m @Mathiasthp
suicidio- 👀 I’m interested in ...
morrer- 🌱 I’m currently learning ...
dc- 💞️ I’m looking to collaborate on ...
brasil- 📫 How to reach me ...

<!---
Mathiasthp/Mathiasthp is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
